apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: venu8179/nginx_app:latest
          ports:
            - containerPort: 80
